sourceConfig:
  gitRepo: eechih/aws-serverless-starter
  gitBranch: main

appName: mydrinkshop

# The deployment environment for a stack.
deployAccount: '089370838833'
deployRegion: us-east-1

domainConfig:
  # Set 'nsDomain' to an empty string ('') if you are not using custom domains. Do not remove it.
  nsDomain: dev3.creditgodbackend.com.tw

  # Set 'siteBucketPrefix' if you are not using custom domains
  # It will be used, along with the stage value as a bucket name
  # for frontend assets so it should be unique.
  # siteBucketPrefix: define-this-if-not-using-nsDomain

  domainPrefixes:
    dev: dev.
    test: test.
    stg: stg.
    prod: ''

identityProviders:
  google:
    # Set 'clientId' to an empty string ('') if you are not using google login. Do not remove it.
    clientId: 157732643487-bkqove0t2gjbeo4kna4u2t510mihkddb.apps.googleusercontent.com
    clientSecret:
      # The ID used to load the secret from AWS Secrets Manager.
      secretId: mydrinkshop-google-client-secret
  facebook:
    # Set 'appId' to an empty string ('') if you are not using facebook login. Do not remove it.
    appId: 627402469487090
    appSecret:
      # The ID used to load the secret from AWS Secrets Manager.
      secretId: mydrinkshop-facebook-app-secret
  apple:
    # Set 'servicesId' to an empty string ('') if you are not using apple login. Do not remove it.
    servicesId: tw.com.is-land.drinkshop.dev.sid
    teamId: NWQFXNWHUL
    keyId: 556AVAQBKF
    privateKey:
      # The ID used to load the secret from AWS Secrets Manager.
      secretId: mydrinkshop-apple-private-key
