# This file must be updated, committed and pushed for your
# SLIC Starter-based application deployment to work
sourceRepo:
  # This should be changed to match your own repo and branch
  owner: eechih
  name: aws-serverless-starter
  branch: main

domainConfig:
  # Set 'nsDomain' to an empty string ('') if you are not using custom domains. Do not remove it.
  nsDomain: sliclists.com

  # Set 'siteBucketPrefix' if you are not using custom domains
  # It will be used, along with the stage value as a bucket name
  # for frontend assets so it should be unique.
  # siteBucketPrefix: define-this-if-not-using-nsDomain

  domainPrefixes:
    dev: dev.
    stg: stg.
    prod: ''
    local: ''
