gitRepo: eechih/aws-serverless-starter
gitBranch: main
appName: mydrinkshop

domainConfig:
  # Set 'nsDomain' to an empty string ('') if you are not using custom domains. Do not remove it.
  #nsDomain: mydrinkshop.com

  # Set 'siteBucketPrefix' if you are not using custom domains
  # It will be used, along with the stage value as a bucket name
  # for frontend assets so it should be unique.
  # siteBucketPrefix: define-this-if-not-using-nsDomain

  domainPrefixes:
    dev: dev.
    stg: stg.
    prod: 'prod.'
    local: ''
