version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      # trigger the unit tests here
      - echo 'Running unit tests'
      - npm install
      - npm run test
